name: StArt OS Android 10 GSI Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depolama Alanı Aç
        run: |
          docker rmi $(docker images -q)
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          sudo apt-get clean

      - name: Gerekli Araçları Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libc6-dev libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev g++-multilib gcc-multilib lib32ncurses5-dev lib32readline-dev lib32z1-dev python3

      - name: Repo Aracını Kur
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: StArt OS Kodlarını İndir
        run: |
          mkdir startos
          cd startos
          git config --global user.name "KayraKonen2015"
          git config --global user.email "kayra@example.com"
          repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
