name: StArt-OS-Full-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Kodları Getir
        uses: actions/checkout@v3

      - name: Sistemi Hazırla ve Yer Aç
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl python3 libssl-dev
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          echo "Sistem inşaat için temizlendi."

      - name: Repo Aracını Kur
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Kaynak Kodları İndir (Lineage 17.1)
        run: |
          mkdir build && cd build
          git config --global user.name "Kayra"
          git config --global user.email "kayra@example.com"
          repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --depth=1
          repo sync -c -j8 --force-sync --no-clone-bundle --no-tags

      - name: StArt OS Yamalarını Uygula
        run: |
          cd build
          # Burada sistemin ismini ve ayarlarını StArt OS olarak değiştiriyoruz
          sed -i 's/LineageOS/StArt OS/g' build/make/core/Makefile
          echo "Sistem kimliği StArt OS olarak güncellendi."

      - name: GSI İmajını Oluştur
        run: |
          cd build
          source build/envsetup.sh
          lunch lineage_arm64-userdebug
          make systemimage -j8

      - name: Hazır Yazılımı Dışarı Aktar
        uses: actions/upload-artifact@v3
        with:
          name: StArt-OS-V1-Image
          path: build/out/target/product/generic_arm64/system.img
